### ISSUE TITLE
https://github.com/JeffreyBenjaminBrown/hode/

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [willbasky/Awesome-list-of-Haskell-mentors#13]
Hode is a hypergraph editor.

Outside of the UI, the core of the application is Hode.Rslt.Types, which defines the hypergraph, and Hode.Hash.Types, which defines the query language. 

I can't call myself a beginner, and I can't call this a small project, but feedback from a wise person would nonetheless be greatly appreciated.

**Comment by willbasky** [comment]
Hi, @JeffreyBenjaminBrown 
Here is not so popular place to fetch a feedback, I guess. I recommend you [Haskell channel in reddit](https://www.reddit.com/r/haskell/). 
Btw, would you like to add your project here?

**Comment by JeffreyBenjaminBrown** [comment]
Thanks, Vladislav!

> would you like to add your project here?

Meaning to this repo? I don't see where to do that.

**Comment by willbasky** [comment]
Just edit README file.

**Comment by willbasky** [comment]
If you'd like to mentor developers, of course.

**Comment by JeffreyBenjaminBrown** [comment]
Oh I see, and volunteeer to be a mentor. I'm afraid I can't make a promise like that this year. I very much appreciate the offer, though.

**Comment by willbasky** [comment]
I see. Come back next year, then! :)
